---
functional:
  - пользователь может зарегистрироваться с помощью электронной почты и пароля
  - пользователь может войти через GitHub или Discord
  - у пользователя есть возможность создать новую игру c другим пользователем или ботом
  - пользователь может ждать второго игрока или поделиться ссылкой на игру
  - игра должна быть доступной для подключения для других пользователей
  - если второй игрок присоединяется к игре, игроки должны перейти в игровое поле
  - у пользователя должна быть возможность выбрать язык программирования (Clojure, C++, C#, Dart, Elixir, Golang, Haskell, Java, Kotlin, Node.js, Php, Phyton, Ruby, Rust, Typescript)
  - в игровом поле должны отображаться два редактора, свой и соперника
  - в игровом поле должны отображаться задание, время игры и чат
  - каждый игрок должен иметь возможность видеть код своего соперника в режиме он-лайн
  - каждый игрок должен иметь кнопку для проверки своего решения
  - если один игрок вылетает из игры, второй может продолжать играть, а первый переподключиться, пока игра не закончена
  - когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры
  - победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у него появилась
  - соперник может выйти, а может доиграть до конца
  - когда оба игрока вышли, игра считается полностью законченной и удаляется из памяти
non-functional:
  - cайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - cайт должен быть безопасным и защищать данные пользователя
  - cайт должен быть удобным на мобильном устройстве
  - cайт должен быть протестирован на совместимость с последними версиями браузеров Google Chrome, Firefox, Safari, Opera
  - cайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей) 
implicit:
  - у игры должна быть документация или подсказки для быстрого освоения игры
  - в игре должен быть выбор задач по сложности и тематике
  - задачи должны быть проверены на корректность
  - база задач должна регулярно обновляться
  - наличие чата для обсуждения и обмена опытoм

